name: Trigger auto deployment for containerapp02

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/containerapp02-AutoDeployTrigger-bc080532-5a9e-4ad7-a89e-59b66527755e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: hub.docker.com/repository/docker/bhuvanprasad
          username: ${{ secrets.CONTAINERAPP02_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP02_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hub.docker.com/repository/docker/bhuvanprasad/todo-dev:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP02_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerapp02 -g Containers --server hub.docker.com/repository/docker/bhuvanprasad --username  ${{ secrets.CONTAINERAPP02_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP02_REGISTRY_PASSWORD }}
            az containerapp update -n containerapp02 -g Containers --image hub.docker.com/repository/docker/bhuvanprasad/todo-dev:${{ github.sha }}
